modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "Attribution-NonCommercial-ShareAlike 4.0 International"

[[mods]]
modId = "buzzydrones"
version = "${version}"
displayName = "Buzzy Drones"
authors = ["HexagonNico", "ZestyBlaze"]
description = '''
A Minecraft Mod that adds drones to move items between containers
'''
#logoFile = ""

[[dependencies.buzzydrones]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.buzzydrones]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.buzzydrones]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"